# Generated by Django 5.2.3 on 2025-07-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0004_gameroom_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='host',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player1_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player2_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='questions_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
