# Generated by Django 5.2.3 on 2025-07-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0005_remove_gameroom_host_gameroom_player1_finished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='questions_deleted',
        ),
    ]
