# Generated by Django 5.2.3 on 2025-07-07 21:27

import game_room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0006_remove_gameroom_questions_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='room_id',
            field=models.CharField(default=game_room.models.generate_room_id, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
